[[constraint]]
  name = "github.com/gorilla/handlers"
  source = "https://github.com/gorilla/handlers"
  version = "1.2.0"

[[constraint]]
  name = "goji.io"
  source = "https://github.com/goji/goji"
  version = "2.0.0"

[[constraint]]
  name = "github.com/coocood/freecache"
  source = "https://github.com/coocood/freecache"
  version = "1.0.1"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  source = "https://github.com/go-ldap/ldap"
  version = "2.5.1"

